### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by fitojb**

### CODE REVIEW

**Comment by almostearthling** [comment]
Also, I'd like to insert a *Credits* section in the readme file, do you mind if I mention you in it when the translation is ready?

**Comment by fitojb** [comment]
I’ve addressed your remarks in a new commit. Thanks a lot for the review, it provided helpful context!

And thanks for considering crediting me – I’m not of those people who is concerned about credits, but it won’t hurt =)

**Comment by fitojb** [comment]
Whoops, it seems that when I force-pushed my amended commit I caused your comments to disappear (where does one file bugs to GitHub?…)

**Comment by almostearthling** [comment]
No matter for the comments... :wink: However I'm merging the new translation in the master branch: in fact using POs makes things much easier (and actually portable). Thank you again, and of course I'm more than happy to give credit. :+1:

**Comment by almostearthling** [comment]
Fine, I also tested the UI in Spanish: as a matter of controls and positions everything seems to work well! I plan to draft a new release tonight - well, I'm at GMT+1 so the time-of-day connotation may vary. :smile:

**Comment by fitojb** [comment]
Grazie mille!

**Pull request merged**
